// lib/mockData/classes.ts
import { FitnessClass } from '../types/class';

// Helper to create dates relative to today
const getDate = (daysFromNow: number, hour: number, minute: number = 0): Date => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  date.setHours(hour, minute, 0, 0);
  return date;
};

export const mockClasses: FitnessClass[] = [
  // User's enrolled classes
  {
    id: '1',
    name: 'Morning Yoga Flow',
    type: 'yoga',
    instructor: 'Sarah Johnson',
    instructorImage: '👩‍🏫',
    startTime: getDate(0, 9, 0),
    endTime: getDate(0, 10, 0),
    duration: 60,
    capacity: 20,
    enrolled: 15,
    difficulty: 'beginner',
    location: 'Studio A',
    description: 'Start your day with energizing yoga poses and breathing exercises.',
    equipment: ['Yoga mat', 'Block'],
    rating: 4.8,
    reviewCount: 128,
    status: 'enrolled',
    userStatus: 'enrolled',
  },
  {
    id: '2',
    name: 'HIIT Intensity',
    type: 'hiit',
    instructor: 'Mike Torres',
    instructorImage: '👨‍🏫',
    startTime: getDate(1, 18, 0),
    endTime: getDate(1, 19, 0),
    duration: 60,
    capacity: 15,
    enrolled: 8,
    difficulty: 'advanced',
    location: 'Studio B',
    description: 'High-intensity interval training to push your limits.',
    equipment: ['Dumbbells', 'Mat'],
    rating: 4.9,
    reviewCount: 95,
    status: 'enrolled',
    userStatus: 'enrolled',
  },
  {
    id: '3',
    name: 'Boxing Fundamentals',
    type: 'boxing',
    instructor: 'John Davis',
    instructorImage: '🥊',
    startTime: getDate(3, 7, 0),
    endTime: getDate(3, 8, 0),
    duration: 60,
    capacity: 12,
    enrolled: 9,
    difficulty: 'intermediate',
    location: 'Boxing Ring',
    description: 'Learn proper boxing technique and get an incredible workout.',
    equipment: ['Gloves', 'Hand wraps'],
    rating: 4.7,
    reviewCount: 67,
    status: 'enrolled',
    userStatus: 'enrolled',
  },

  // Available classes
  {
    id: '4',
    name: 'Power Spin',
    type: 'spin',
    instructor: 'Lisa Martinez',
    instructorImage: '🚴',
    startTime: getDate(0, 18, 0),
    endTime: getDate(0, 19, 0),
    duration: 60,
    capacity: 20,
    enrolled: 20,
    difficulty: 'intermediate',
    location: 'Spin Studio',
    description: 'High-energy cycling class with motivating music.',
    equipment: ['Spin bike'],
    rating: 4.6,
    reviewCount: 89,
    status: 'full',
    userStatus: null,
  },
  {
    id: '5',
    name: 'Pilates Core',
    type: 'pilates',
    instructor: 'Emma Wilson',
    instructorImage: '🧘‍♀️',
    startTime: getDate(0, 10, 30),
    endTime: getDate(0, 11, 30),
    duration: 60,
    capacity: 15,
    enrolled: 7,
    difficulty: 'beginner',
    location: 'Studio A',
    description: 'Strengthen your core with controlled movements.',
    equipment: ['Mat', 'Resistance band'],
    rating: 4.8,
    reviewCount: 112,
    status: 'available',
    userStatus: null,
  },
  {
    id: '6',
    name: 'Cardio Dance Party',
    type: 'dance',
    instructor: 'Carlos Rodriguez',
    instructorImage: '💃',
    startTime: getDate(1, 19, 0),
    endTime: getDate(1, 20, 0),
    duration: 60,
    capacity: 25,
    enrolled: 18,
    difficulty: 'beginner',
    location: 'Studio B',
    description: 'Dance your way to fitness with fun choreography.',
    equipment: ['None'],
    rating: 4.9,
    reviewCount: 156,
    status: 'available',
    userStatus: null,
  },
  {
    id: '7',
    name: 'Strength Training 101',
    type: 'strength',
    instructor: 'Alex Thompson',
    instructorImage: '💪',
    startTime: getDate(2, 6, 0),
    endTime: getDate(2, 7, 0),
    duration: 60,
    capacity: 15,
    enrolled: 12,
    difficulty: 'intermediate',
    location: 'Weight Room',
    description: 'Build muscle and increase strength with proper form.',
    equipment: ['Barbells', 'Dumbbells', 'Bench'],
    rating: 4.7,
    reviewCount: 78,
    status: 'available',
    userStatus: null,
  },
  {
    id: '8',
    name: 'Sunset Yoga',
    type: 'yoga',
    instructor: 'Maya Patel',
    instructorImage: '🧘',
    startTime: getDate(2, 17, 30),
    endTime: getDate(2, 18, 30),
    duration: 60,
    capacity: 20,
    enrolled: 19,
    difficulty: 'intermediate',
    location: 'Rooftop Studio',
    description: 'Relax and unwind with gentle yoga as the sun sets.',
    equipment: ['Yoga mat'],
    rating: 5.0,
    reviewCount: 203,
    status: 'available',
    userStatus: null,
  },
  {
    id: '9',
    name: 'Aqua Fitness',
    type: 'swimming',
    instructor: 'Jennifer Lee',
    instructorImage: '🏊',
    startTime: getDate(3, 8, 0),
    endTime: getDate(3, 9, 0),
    duration: 60,
    capacity: 12,
    enrolled: 5,
    difficulty: 'beginner',
    location: 'Pool',
    description: 'Low-impact full-body workout in the water.',
    equipment: ['Swimsuit'],
    rating: 4.5,
    reviewCount: 45,
    status: 'available',
    userStatus: null,
  },
  {
    id: '10',
    name: 'Advanced HIIT',
    type: 'hiit',
    instructor: 'Mike Torres',
    instructorImage: '👨‍🏫',
    startTime: getDate(4, 6, 30),
    endTime: getDate(4, 7, 30),
    duration: 60,
    capacity: 15,
    enrolled: 14,
    difficulty: 'advanced',
    location: 'Studio B',
    description: 'Extreme workout for experienced athletes.',
    equipment: ['Kettlebells', 'Battle ropes'],
    rating: 4.8,
    reviewCount: 62,
    status: 'available',
    userStatus: null,
  },
];

// Helper functions
export const getEnrolledClasses = (): FitnessClass[] => {
  return mockClasses.filter(c => c.userStatus === 'enrolled');
};

export const getAvailableClasses = (): FitnessClass[] => {
  return mockClasses.filter(c => c.userStatus !== 'enrolled');
};

export const getClassById = (id: string): FitnessClass | undefined => {
  return mockClasses.find(c => c.id === id);
};
